apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: pomoduck-backend
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: pomoduck-backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: pomoduck-backend
          image: "registry.digitalocean.com/pomoduck/pomoduck-backend:v0.1.0-prod"
          ports:
            - name: http
              containerPort: 80
