apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomoduck-backend
spec:
  selector:
    matchLabels:
      app: pomoduck-backend
  template:
    metadata:
      labels:
        app: pomoduck-backend
    spec:
      containers:
        - name: pomoduck-backend
          image: "registry.digitalocean.com/pomoduck/pomoduck-backend:v0.1.0-prod"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
          - containerPort: 3001
          env:
          - name: DB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: DB_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: pomoduck-backend
  ports:
    - port: 3001
      targetPort: 3001