apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomoduck-backend
spec:
  selector:
    matchLabels:
      app: pomoduck-backend
  template:
    metadata:
      labels:
        app: pomoduck-backend
    spec:
      containers:
        - name: pomoduck-backend
          imagePullPolicy: Always
          image: "registry.digitalocean.com/pomoduck/pomoduck-backend:v1.0.0-prod"
          ports:
            - containerPort: 3001
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: pomoduck-backend
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: express-configmap
data:
  EXPRESS_SERVICE: express-service.default.svc.cluster.local
